apiVersion: v1
kind: Service
metadata:
  namespace: sample
  name: config-application
spec:
  type: NodePort
  selector:
    app: config-application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000